### PR TITLE
Search Filters for Searching Our mongo

### PR DESCRIPTION
**Pull request by witehound**
- updated server service 
- upddated fe code

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Nice work here, the only thing i think Most Items is not functioning for me? Are you seeing this work on your side ?

**Comment by witehound** [comment]
Yes! I have packs with zero items and then one with an actual item and it filters are you using the demo ?

**Comment by witehound** [comment]
@andrew-bierman fixed looks like already existing code had a bug

**Review by andrew-bierman — APPROVED** [review]
looks good

**Pull request merged**
