### PR TITLE
changes in usePagination

### PR DESCRIPTION
**Pull request by Isthisanmol**

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol - the mobile app crashes while trying to access the Items Page. I've included a video for reference. Thanks for looking into this!

https://github.com/andrew-bierman/PackRat/assets/122357250/d4f0cf06-fa37-47d7-9e78-bb81c4339d30

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol - the mobile app crashes while trying to access the Items Page. I've included a video for reference. Thanks for looking into this!
> 16.mp4

Please check for the latest commit and update if there are any issues.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, I've noticed a few areas that need updates:

- [ ] Can we adjust the item text so it doesn't overlap onto the next line? For example, the word "Essentials" has its 'S' on the next line.
image

- [ ] I selected 10 items, but the table only previews 7. Please update.
- [ ] Please adjust the layout so that the "Choose a value" text doesn't overlap with the option menu below it.
- [ ] Update the "Choose a value" option so that it doesn't occupy the entire screen. Perhaps we could make it a small pop-up instead.
image

Thanks again!

**Comment by andrew-bierman** [comment]
> Hi @Isthisanmol, I've noticed a few areas that need updates:
> 
> 
> 
> - [ ] Can we adjust the item text so it doesn't overlap onto the next line? For example, the word "Essentials" has its 'S' on the next line.
> 
> image
> 
> 
> 
> - [ ] I selected 10 items, but the table only previews 7. Please update.
> 
> - [ ] Please adjust the layout so that the "Choose a value" text doesn't overlap with the option menu below it.
> 
> - [ ] Update the "Choose a value" option so that it doesn't occupy the entire screen. Perhaps we could make it a small pop-up instead.
> 
> image
> 
> 
> 
> Thanks again! 

I merged this so it did not get stale, but please see these comments @Isthisanmol when you are free :)

**Comment by Isthisanmol** [comment]
> > Hi @Isthisanmol, I've noticed a few areas that need updates:
> > 
> > * [ ]  Can we adjust the item text so it doesn't overlap onto the next line? For example, the word "Essentials" has its 'S' on the next line.
> > 
> > image
> > 
> > * [ ]  I selected 10 items, but the table only previews 7. Please update.
> > * [ ]  Please adjust the layout so that the "Choose a value" text doesn't overlap with the option menu below it.
> > * [ ]  Update the "Choose a value" option so that it doesn't occupy the entire screen. Perhaps we could make it a small pop-up instead.
> > 
> > image
> > Thanks again!
> 
> I merged this so it did not get stale, but please see these comments @Isthisanmol when you are free :)
 
 Hi, @EngrAJ8888 Fixed these already in PR:  #984 but the last one is  a component that uses tamagui sheet and this dropdown is used in the entire app. Should I make another component for this one only?

**Comment by andrew-bierman** [comment]
@Isthisanmol you can keep current sheet version for now but fix any remaining issues AJ reported for this. 

Let’s discuss a separate PR that would be tamagui dropdown on web and zeego dropdown on native. It will be like the component we have that uses popover for web and zeego for native I imagine.

**Comment by Isthisanmol** [comment]
> @Isthisanmol you can keep current sheet version for now but fix any remaining issues AJ reported for this.
> 
> Let’s discuss a separate PR that would be tamagui dropdown on web and zeego dropdown on native. It will be like the component we have that uses popover for web and zeego for native I imagine.

Thank you for the suggestion! I think creating a component that uses Tamagui Dropdown on web and Zeego Dropdown on native platforms would indeed streamline our UI/UX across different environments. Should I implement that?

**Pull request merged**
