### PR TITLE
Fix FAB content not collapsing

### PR DESCRIPTION
**Pull request by mikib0**

### CODE REVIEW

**Review by andrew-bierman — APPROVED** [review]

**Review by JewelTee — COMMENTED** [review]
@mikib0 hi, the issue persists

**Comment by mikib0** [comment]
Hi @JewelTee, please check again now

**Comment by JewelTee** [comment]
@mikib0 issue is fixed now. However, if you turn to a different screen the popup button does not collapse automatically. Can we update this? Thank you!

**Comment by mikib0** [comment]
@JewelTee Ha, I see. Let me fix that.

**Pull request merged**
