### PR TITLE
Changes in style

### PR DESCRIPTION
**Pull request by Isthisanmol**
Changes in style in FeedSearchFilter, AddPack,  packtable.style and  UserDetailList

### CODE REVIEW

**Comment by jeweltee** [comment]
@Isthisanmol thanks for this update, but can we resize the "Add Pack" button, make it a bit smaller, and also fix the alignment of the text to make it centered? Please see the images below, thanks! 
438203827_1506735950191796_4607191236402845135_n


441153037_462019082883477_8273024675211487787_n

**Comment by Isthisanmol** [comment]
> @Isthisanmol thanks for this update, but can we resize the "Add Pack" button, make it a bit smaller, and also fix the alignment of the text to make it centered? Please see the images below, thanks! 438203827_1506735950191796_4607191236402845135_n
> 
> 441153037_462019082883477_8273024675211487787_n

Is this for mobile app?

**Comment by Isthisanmol** [comment]
> @Isthisanmol Yes, its the mobile app UI

Fixed this. Please check.

**Comment by jeweltee** [comment]
> > @Isthisanmol Yes, its the mobile app UI
> 
> Fixed this. Please check.

Thanks, the update looks good!

**Comment by jeweltee** [comment]
@andrew-bierman - this is good to go for merging!

**Review by andrew-bierman — APPROVED** [review]

**Review by andrew-bierman — APPROVED** [review]

**Pull request merged**
