### PR TITLE
Fix map preview and table layout

### PR DESCRIPTION
**Pull request by MuhammadHassan03**
@jeweltee Fixed in create Trip Page. Here's the list

_Map Preview_
_Table Layout_

Please Check it out

### CODE REVIEW

**Comment by jeweltee** [comment]
@MuhammadHassan03 The Map Preview and Viewing Owner in Trip Page are now fixed, however, I want to clarify the tables. Let's integrate the component from Tamagui Bento UI. And also can we update this PR with the latest andrew_testing branch, I think the branch in this PR is behind the latest andrew_testing. Thank You!

**Comment by MuhammadHassan03** [comment]
> @MuhammadHassan03 The Map Preview and Viewing Owner in Trip Page are now fixed, however, I want to clarify the tables. Let's integrate the component from Tamagui Bento UI. And also can we update this PR with the latest andrew_testing branch, I think the branch in this PR is behind the latest andrew_testing. Thank You! 

Sure, i am working to integrate table from Bento UI and i'll update this one to the latest one...

**Comment by MuhammadHassan03** [comment]
> > @MuhammadHassan03 The Map Preview and Viewing Owner in Trip Page are now fixed, however, I want to clarify the tables. Let's integrate the component from Tamagui Bento UI. And also can we update this PR with the latest andrew_testing branch, I think the branch in this PR is behind the latest andrew_testing. Thank You! 
> 
> @jeweltee Sure, i am working to integrate table from Bento UI and i'll update this one to the latest one...

**Comment by andrew-bierman** [comment]
- [ ] Merge testing into here, resolve conflicts
- [ ] Remove server changes such as deleting migrations

**Comment by MuhammadHassan03** [comment]
> * [x]  Merge testing into here, resolve conflicts
> * [x]  Remove server changes such as deleting migrations

Hey @andrew-bierman , i am done with the mentioned changes above. Please Check it out

**Comment by andrew-bierman** [comment]
- [ ] Fix failing builds

**Comment by MuhammadHassan03** [comment]
> * [x]  Fix failing builds

@andrew-bierman The Cloudflare build is fixed in this PR with latest commit in this PR

https://github.com/andrew-bierman/PackRat/pull/985

please check it out

**Pull request closed without merging**
