### PR TITLE
[#841] Bad UI fixes and improvements 

### PR DESCRIPTION
**Pull request by mikeCyb**
**fixes**
1. Edit/ delete column is removed in global items.
2. Search menu dropdown overlapping is now fixed.

Additionally it has Trip creation functionality fixes[#883], But I have asked PR last week for them.

### CODE REVIEW

**Comment by jeweltee** [comment]
@mikeCyb hi! thanks for this update. Regarding the search menu dropdown, I noticed that when searching items in global, the form for items moves down to prevent overlap. Can we update this so that the form containing the items doesn't move downward? We could do it like the search menu dropdown on the Create Trips page or something similar. Thank You! 

The Screenshot below is the search menu dropdown on the Create Trips Page
aa0e4e1b-004f-43d1-96df-eae1fa5db418

**Comment by mikeCyb** [comment]
@jeweltee : Thank you for the clarification; it will be addressed.

**Comment by jeweltee** [comment]
@mikeCyb hi! since you opened a new ticket addressing the issue on the search menu dropdown (#947), can we update this PR and remove the update on the Search menu dropdown? so this will only be for the 'Edit/ delete column is removed in global items.' To avoid conflicts.  Thanks!

**Comment by jeweltee** [comment]
@mikeCyb hi! Just want to follow up on this. Thanks!

**Comment by jeweltee** [comment]
@mikeCyb hi! Just want to follow up on this. Thanks!

**Pull request closed without merging**
