### PR TITLE
Virtualized

### PR DESCRIPTION
**Pull request by ArbazYousuf**
1. Virtualized resolve in trip and feed screen
2. Remove unnecessary import

### CODE REVIEW

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
on iOS, the majority of pages are broken or do not scroll. Do you have this issue on your end ?

**Comment by ArbazYousuf** [comment]
Yes Scrollview break in some screens I set them all and change the dropdown from native base to react native picker to resolve virtualized issue

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
I'm still getting a ton of broken pages on my end. Can you please see if you have this issue ? I think the outer view wrapping the slot is causing issues. And the picker is not linking on ios for me

**Comment by andrew-bierman** [comment]
Screenshot 2023-07-22 at 10 15 30 AM

**Comment by andrew-bierman** [comment]
Search section on dashboard no longer appears

**Comment by andrew-bierman** [comment]
> Screenshot 2023-07-22 at 10 15 30 AM

Trips page, could be a local only issue

**Review by andrew-bierman — APPROVED** [review]
looks good

**Pull request merged**
