### PR TITLE
refactor: refactor custom button

### PR DESCRIPTION
**Pull request by taronaleksanian**

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Can we replace custom button with just our normal button from @packrat/ui ? Is it doing anything differently?

**Comment by taronaleksanian** [comment]
> Can we replace custom button with just our normal button from @packrat/ui ? Is it doing anything differently?

It has its styles, I think we can have Button variants later. Probably with tagmaui theme config, I just tried to keep the version that we have now, and collect all the buttons we have now, so later creating variants will be easier

**Comment by taronaleksanian** [comment]
> Can we replace custom button with just our normal button from @packrat/ui ? Is it doing anything differently?

actually, you are right, I though it was created as a button variant, but after reviewing it carefully I saw that there is nothing about colors or sizes

**Review by andrew-bierman — APPROVED** [review]
good work, we should at some point refactor so file structure of button matches other UI components. But that can be a later task this is fine for now

**Pull request merged**
