### PR TITLE
Use tamagui media for responsiveness

### PR DESCRIPTION
**Pull request by Isthisanmol**
Replace platform.os and screenwidth logic by tamagui built in method

### CODE REVIEW

**Comment by andrew-bierman** [comment]
This is much cleaner, we should probs wrap this hook so we are importing it from either hooks or ui dir 

Also wanted to flag the $gt prop we have with tamagui also if helpful

**Review by JewelTee — COMMENTED** [review]
The UI on Mobile Web View is broken on some pages and also when clicking on "Create a Trip" from the home page it 
gives you an error. Please see images below : 
image
image
image

**Comment by JewelTee** [comment]
Adding these issues I encountered on Android Mobile App:

- [ ] App crashes when clicking on "Create a pack" and "Items" 
- [ ] The UI on the homepage: 
Screenshot_20240614_193012

**Comment by Isthisanmol** [comment]
> The UI on Mobile Web View is broken on some pages and also when clicking on "Create a Trip" from the home page it gives you an error. Please see images below : image image image

Thanks for reviewing! I'll fix these.

**Comment by JewelTee** [comment]
@Isthisanmol hi. There are still persisting issues on the Mobile Web View, The Packs,Trips,Feed page shows this error: 

IMG_5312


Also, can we align the 'Add item' button with the Sort option element. Thank You!

IMG_5313

**Comment by JewelTee** [comment]
@Isthisanmol everything looks good. Thank You!

@andrew-bierman this is ready for merging 👍🏻

**Review by andrew-bierman — APPROVED** [review]
nice job :)

**Pull request merged**
