### PR TITLE
Feature native

### PR DESCRIPTION
**Pull request by vipin4771234**
Hey Andrew Please merge the pull request

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Cards still say View Owner?

**Comment by andrew-bierman** [comment]
Are you able to open the pack of another user? my screen now goes blank after the redirect ?

**Comment by andrew-bierman** [comment]
signed in as demo user on preview PR. click on vipin pack (or any other pack of another user), goes blank. Do you have this issue also ?

**Comment by vipin4771234** [comment]
> Cards still say View Owner?

fixed it

**Comment by vipin4771234** [comment]
> Are you able to open the pack of another user? my screen now goes blank after the redirect ?

fixed it

**Comment by vipin4771234** [comment]
> signed in as demo user on preview PR. click on vipin pack (or any other pack of another user), goes blank. Do you have this issue also ?

fixed it

**Comment by vipin4771234** [comment]
Please verify

**Review by andrew-bierman — APPROVED** [review]

**Pull request merged**
