### PR TITLE
homepage improvements 

### PR DESCRIPTION
**Pull request by mikeCyb**

### CODE REVIEW

**Comment by mikeCyb** [comment]
Hey @JewelTee, this is the updated version of my PR. Check it out and let me know your feedback.

**Review by JewelTee — COMMENTED** [review]
@mikeCyb hi is the nav bar included in this PR? I don't seem to see it on my end. And also the alignment of the components on the Feed, Packs,Trips and Items page were changed. Please see images below, Thank You! 
Screenshot 2024-06-12 at 15 12 20
Screenshot 2024-06-12 at 15 14 17

**Comment by mikeCyb** [comment]
@JewelTee , The issue is now fixed. Please check it out and let me know your feedback.

**Comment by JewelTee** [comment]
@mikeCyb thanks for the update, I just noticed the search menu is missing on the packs details page. Could you please check it out? 
Screenshot 2024-06-13 at 12 11 50

**Comment by EngrAJ8888** [comment]
Hi @mikeCyb , please add the item below to the homepage update as well.

Update feed section in the homepage, please see the photo below for reference.
image

Thanks!

**Comment by EngrAJ8888** [comment]
Hi @mikeCyb , thanks for the quick update! Please complete the item raised by @JewelTee and this will be good for merging.

**Comment by mikeCyb** [comment]
@EngrAJ8888 Thanks. I don't think the issue is on my side, and I have informed @JewelTee about it.

**Comment by JewelTee** [comment]
@andrew-bierman this is ready for merging 👍🏻

**Review by andrew-bierman — APPROVED** [review]

**Pull request merged**
