### PR TITLE
added date range picker in trip create page

### PR DESCRIPTION
**Pull request by Sangeeta369jangir**
added date range picker on create trip page. for date range picker using 'react-native-paper-dates'  package.
image

Date Range picker:
image

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Do we support date natively in mongo now? I think that could be powerful feature. 

Also how do we display this data on trip details page?

**Comment by andrew-bierman** [comment]
Any option to customize colors or size of modal ? overall it looks good though!

**Comment by andrew-bierman** [comment]
Lot of console errors on web and ios on my end. Do you get these ?

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
See comments

**Comment by Sangeeta369jangir** [comment]
> Do we support date natively in mongo now? I think that could be powerful feature.
> 
> Also how do we display this data on trip details page?

storing dates in Date type object in mongo.
added start and end dates on trip details page

**Comment by Sangeeta369jangir** [comment]
> Lot of console errors on web and ios on my end. Do you get these ?

fixed.

**Comment by andrew-bierman** [comment]
> Any option to customize colors or size of modal ? overall it looks good though!

Let's just see if we can fix this then good to merge

**Comment by Sangeeta369jangir** [comment]
> Any option to customize colors or size of modal ? overall it looks good though!

There are no options to resize, and force full override of css might break in ios/android devices. 
even colors are added via inline css, there are no options to override, or provide a custom css class name.

**Review by andrew-bierman — APPROVED** [review]
lgtm

**Pull request merged**
