### PR TITLE
Test pr branch

### PR DESCRIPTION
**Pull request by Isthisanmol**

### CODE REVIEW

**Review by taronaleksanian — APPROVED** [review]

**Comment by JewelTee** [comment]
@Isthisanmol Hi thanks for the updates, here are additional issues I encountered in this PR:

- [ ] Adjust the size of these components:
IMG_5271


- [ ]  when you try to open a Trip or a Pack it shows an error. Please see image below
IMG_5270


- [ ] Appearance and Logout buttons are missing from the Menu

**Review by andrew-bierman — APPROVED** [review]
nice job, lgtm. Fix the issues listed in the PR then this is good to merge when you are ready

**Comment by Isthisanmol** [comment]
> @Isthisanmol Hi thanks for the updates, here are additional issues I encountered in this PR:
> 
>     * [ ]  Adjust the size of these components:
>       IMG_5271
> 
>     * [ ]   when you try to open a Trip or a Pack it shows an error. Please see image below
>       IMG_5270
> 
>     * [ ]  Appearance and Logout buttons are missing from the Menu

Hi @JewelTee, I have updated the first item and the rest of them are working fine on my end. Would you please check again and update me if there are issues?

**Comment by andrew-bierman** [comment]
Merging this in, @JewelTee follow up if your reported issues persist please

**Comment by JewelTee** [comment]
@Isthisanmol @andrew-bierman  Issues are now fixed, exept for the Appearance and Logout buttons are missing from the Menu.

**Comment by andrew-bierman** [comment]
Actions columns blank on web possibly? Actually it seems to be when user doesn't own the pack. We should hide actions in this case. 

Responsiveness on table seems to cut content off before it switches to mobile view

**Comment by Isthisanmol** [comment]
> @Isthisanmol @andrew-bierman Issues are now fixed, exept for the Appearance and Logout buttons are missing from the Menu.

I'll check it out.

**Comment by Isthisanmol** [comment]
> Actions columns blank on web possibly? Actually it seems to be when user doesn't own the pack. We should hide actions in this case.
> 
> Responsiveness on table seems to cut content off before it switches to mobile view

I'll work on that.

**Comment by JewelTee** [comment]
> > @Isthisanmol @andrew-bierman Issues are now fixed, exept for the Appearance and Logout buttons are missing from the Menu.
> 
> The buttons are visible on my endScreenshot from 2024-06-11 11-30-14

Sorry, I meant for the mobile web. The Appearance and Logout buttons are missing from the Menu on on the mobile web.

**Comment by Isthisanmol** [comment]
> > > @Isthisanmol @andrew-bierman Issues are now fixed, exept for the Appearance and Logout buttons are missing from the Menu.
> > 
> > 
> > The buttons are visible on my endScreenshot from 2024-06-11 11-30-14
> 
> Sorry, I meant for the mobile web. The Appearance and Logout buttons are missing from the Menu on on the mobile web.

Sorry, I didn't check that. I'll fix that now.

**Pull request merged**
