### PR TITLE
Feat/bento theme integration

### PR DESCRIPTION
**Pull request by taronaleksanian**
- [x] Date picker on native fixed

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian - I've reviewed the latest preview link on both web and mobile, but it appears I can't search for locations when creating a trip. Additionally, the layout seems a bit off on the web version. Could you take a look into this? Thank you! 

image

**Comment by taronaleksanian** [comment]
Sure will fix it soon

**Comment by jeweltee** [comment]
@taronaleksanian I was able to create a trip on my end, but the layout is indeed a bit off as @EngrAJ8888 mentioned.

**Comment by taronaleksanian** [comment]
Sure @jeweltee thanks

**Comment by taronaleksanian** [comment]
@JewelTee @EngrAJ8888 The issue on the web layout was fixed you can check it out. I used full-screen layout to adjust with the main menu if it works we can use it on the other pages

The next step is the packs/items section on the create trip page, I also noticed some functionality issues there on native app, which will be fixed too

Then I Will continue fixing based on the issues reported by you in the repo

**Comment by JewelTee** [comment]
@taronaleksanian hi! the layout looks better, but can we change the placement of the search bar? I think it looks a bit weird

Screenshot 2024-06-08 at 14 14 44

**Comment by taronaleksanian** [comment]
@JewelTee Sure, which position do you think is a better position?

**Comment by JewelTee** [comment]
> position?

Maybe closer to the "Where are you heading?" Text

**Comment by JewelTee** [comment]
> @JewelTee Sure, which position do you think is a better position?

Maybe closer to the "Where are you heading?" Text

**Comment by andrew-bierman** [comment]
Is this good to merge or still waiting on anything ?

**Comment by JewelTee** [comment]
@andrew-bierman I think there are still pending tasks for this PR

**Pull request closed without merging**
