### PR TITLE
Homepage improvements

### PR DESCRIPTION
**Pull request by mikeCyb**
**Improvements** 
1. Click functionality on Packrat Logo 
2. Quick action text improvements 
3. Home page search input adjusted with the width of navbar

### CODE REVIEW

**Comment by mikeCyb** [comment]
@EngrAJ8888 Thanks for the feedback it will get fixed.

**Comment by mikeCyb** [comment]
hey @EngrAJ8888 I have modified it as you said.  Check it now and let me hear your feedback again.

**Comment by EngrAJ8888** [comment]
Hi @mikeCyb, thanks for the update! This looks good to me, and no further updates are needed. Appreciate your work!

@andrew-bierman - this is ready for merging.

Thank you both!

**Comment by EngrAJ8888** [comment]
Hi @mikeCyb , thanks for the update!

@andrew-bierman - this looks good for merging.

Thank you both!

**Review by andrew-bierman — APPROVED** [review]

**Comment by EngrAJ8888** [comment]
Closing this one. The new PR for homepage improvements is #993

**Pull request closed without merging**
