### PR TITLE
Pack templates feature

### PR DESCRIPTION
**Pull request by mikib0**
- [x] Templates screen
- [x] Creating pack from template

#### PR Summary
- Added a "Templates" button on dashboard, which clicking navigates to pack templates screen
- Another button "Browse templates" is added in pack creation screen
- A "Use Template" button in pack template screen allows users to create a pack from a template
- Refactored our Basic table component to be more modular
- Fixed vitest by specifying the env to pick up bindings and variables from

PS: Pack templates are to be seeded directly in to db

### CODE REVIEW

**Review by JewelTee — COMMENTED** [review]
@mikib0 looks good on Web, the template feature is functioning well.

But I haven't tested it on native because I am not able to log in or even register a new account on native.

**Review by EngrAJ8888 — COMMENTED** [review]
@mikib0, this looks good on the web, and the new template feature is working on my end. I am also unable to login/create an account on the native app. Thanks!

**Comment by mikib0** [comment]
Thanks for the review @JewelTee @EngrAJ8888.
We've made some updates to fix the issue. Please try the new builds generated [here](https://github.com/andrew-bierman/PackRat/actions/runs/10949476240?pr=1232).

**Comment by EngrAJ8888** [comment]
Hi @mikib0, I reviewed the updates, but the ready-made templates are not showing. when I click on "Browse Template", no template packs are available. Thanks! 
image

**Comment by taronaleksanian** [comment]
@EngrAJ8888 Hi, Preview builds work only for the development branch, so we need to merge development first. Now we're preparing a demo version on the development branch, We need to get it done first I guess, then add this feature, as it is a large pr

**Comment by taronaleksanian** [comment]
@mikib0 let's also revert changes inside migrations folder we'll add them once we merge this to the prod

**Review by taronaleksanian — APPROVED** [review]

**Pull request merged**
