### PR TITLE
Enhance items table page on web

### PR DESCRIPTION
**Pull request by Isthisanmol**

### CODE REVIEW

**Review by andrew-bierman — APPROVED** [review]
lgtm

**Review by JewelTee — APPROVED** [review]
@Isthisanmol - Everything looks good.

@andrew-bierman - this is ready for merging

**Comment by andrew-bierman** [comment]
Do we still want this PR ? It might have been resolved in your other branch that was merged

**Comment by Isthisanmol** [comment]
> Do we still want this PR ? It might have been resolved in your other branch that was merged

Yes, we don't need this PR.

**Pull request closed without merging**
