### PR TITLE
Feat/cf vectorize initial

### PR DESCRIPTION
**Pull request by andrew-bierman**

### CODE REVIEW

**Comment by andrew-bierman** [comment]
https://github.com/andrew-bierman/PackRat/issues/1002

**Comment by andrew-bierman** [comment]
@MuhammadHassan03 @pinocchio-life-like FYI - I'm merging this in, might need small update on a few of the new http routes

**Review by andrew-bierman — COMMENTED** [review]
Great job here

**Comment by pinocchio-life-like** [comment]
@andrew-bierman Ok, Got it!

**Pull request merged**
