### PR TITLE
:Ui fixes

### PR DESCRIPTION
**Pull request by shahzaib-manzoor**

### CODE REVIEW

**Comment by JewelTee** [comment]
@shahzaib-manzoor  hi thanks fot this update the issues listed below are now fixed.

-  Remove the blank section when viewing all items in the user favorites/trips/packs.

- The menu below is overlapping the change password button, preventing users from changing their password.


While, the other tasks on ticket #970 are still pending.

**Comment by shahzaib-manzoor** [comment]
This one is remaining,
When creating a pack, clicking on the "is public" option should not occupy the entire screen. Instead, make it a floating screen similar to editing an item option in the pack.

**Comment by JewelTee** [comment]
@andrew-bierman this is ready for merging. Thanks!

**Review by andrew-bierman — APPROVED** [review]
nice job :)

**Comment by andrew-bierman** [comment]
This looks good let's just resolve merge conflicts and this is good to ship

**Comment by andrew-bierman** [comment]
@Isthisanmol pls take a look and make sure these changes work with your recent edits - I think there is possibly some overlap on components

**Pull request merged**
