### PR TITLE
Fix profile UI broken on Native

### LINKED ISSUE #1109: Profile Screen UI Broken on Native
**Describe the bug**
- [x] The UI of the Profile Screen is broken

Screenshot_2024-07-18-14-02-13-08_248012cd4184c9416d967f4c08ee0567

Screenshot_2024-07-18-14-02-25-18_248012cd4184c9416d967f4c08ee0567

### PR DESCRIPTION
**Pull request by Tadjaur**
fix #1109

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur - The profile UI is now fixed, but clicking on the 'See All' option causes the app to crash. 
image

**Review by JewelTee — COMMENTED** [review]
@Tadjaur I encountered the same issue @EngrAJ8888 mentioned above.

**Comment by Tadjaur** [comment]
> @Tadjaur I encountered the same issue @EngrAJ8888 mentioned above.

it is now fixed.

**Review by EngrAJ8888 — APPROVED** [review]

**Comment by andrew-bierman** [comment]
Does this break the standard search on Feed screen? If not, then good to merge

**Comment by JewelTee** [comment]
@andrew-bierman No it does not break the standard search on Feed screen. This is good to merge 👍🏻

**Review by JewelTee — APPROVED** [review]

**Pull request merged**
