### PR TITLE
PR without maps and trip components

### PR DESCRIPTION
**Pull request by pinocchio-life-like**
Map and Trip removed because of potential functional change.

### CODE REVIEW

**Comment by andrew-bierman** [comment]
see the ubuntu build errors in GitHub actions

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
style files need .style. some github checks are failing

**Comment by pinocchio-life-like** [comment]
> see the ubuntu build errors in GitHub actions

The Ubuntu build is now successful. Also the .style. extension has been set.

**Review by andrew-bierman — APPROVED** [review]
Nice job

**Pull request merged**
