### PR TITLE
TRPC Integration on Server and Client

### PR DESCRIPTION
**Pull request by raghavyuva**
### **TODO**
- Make use of middlewares isAdmin, authMiddleware in the trpc routers 
- Convert the above middlewares such that they support trpc middleware format
- Write a common function for both REST API's and TRPC router

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Will provide more feedback later. 

For discussion https://trpc.io/docs/server/adapters/express

**Comment by andrew-bierman** [comment]
Are you able to run server on your side? I'm running into TS errors

**Comment by andrew-bierman** [comment]
Deploy logs
```typescript
Aug 30 01:34:47 PM  > packrat@0.0.1 expo:export /opt/render/project/src
Aug 30 01:34:47 PM  > cd client && cp app.example.json app.json && npx expo export --platform web
Aug 30 01:34:47 PM  
Aug 30 01:34:48 PM  Starting Metro Bundler
Aug 30 01:38:08 PM  Web Bundling failed 200148ms
Aug 30 01:38:09 PM  
Aug 30 01:38:09 PM  Error: Unable to resolve module @trpc/server/observable from /opt/render/project/src/client/node_modules/@trpc/client/dist/index.mjs: @trpc/server/observable could not be found within the project or in these directories:
Aug 30 01:38:09 PM    node_modules
Aug 30 01:38:09 PM  > 1 | import { share, observableToPromise } from '@trpc/server/observable';
Aug 30 01:38:09 PM      |                                             ^
Aug 30 01:38:09 PM    2 | import { c as createChain } from './splitLink-4c75f7be.mjs';
Aug 30 01:38:09 PM    3 | export { s as splitLink } from './splitLink-4c75f7be.mjs';
Aug 30 01:38:09 PM    4 | import { T as TRPCClientError } from './TRPCClientError-fef6cf44.mjs';
Aug 30 01:38:09 PM  Error: Unable to resolve module @trpc/server/observable from /opt/render/project/src/client/node_modules/@trpc/client/dist/index.mjs: @trpc/server/observable could not be found within the project or in these directories:
Aug 30 01:38:09 PM    node_modules
Aug 30 01:38:09 PM  > 1 | import { share, observableToPromise } from '@trpc/server/observable';
Aug 30 01:38:09 PM      |                                             ^
Aug 30 01:38:09 PM    2 | import { c as createChain } from './splitLink-4c75f7be.mjs';
Aug 30 01:38:09 PM    3 | export { s as splitLink } from './splitLink-4c75f7be.mjs';
Aug 30 01:38:09 PM    4 | import { T as TRPCClientError } from './TRPCClientError-fef6cf44.mjs';
Aug 30 01:38:09 PM      at ModuleResolver.resolveDependency (/opt/render/project/src/client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
Aug 30 01:38:09 PM      at DependencyGraph.resolveDependency (/opt/render/project/src/client/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
Aug 30 01:38:09 PM      at Object.resolve (/opt/render/project/src/client/node_modules/metro/src/lib/transformHelpers.js:177:21)
Aug 30 01:38:09 PM      at Graph._resolveDependencies (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
Aug 30 01:38:09 PM      at Graph._processModule (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
Aug 30 01:38:09 PM      at runMicrotasks (<anonymous>)
Aug 30 01:38:09 PM      at processTicksAndRejections (internal/process/task_queues.js:95:5)
Aug 30 01:38:09 PM      at async Graph._addDependency (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
Aug 30 01:38:09 PM      at async Promise.all (index 0)
Aug 30 01:38:09 PM      at async Graph._processModule (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
Aug 30 01:38:09 PM  npm ERR! code ELIFECYCLE
Aug 30 01:38:09 PM  npm ERR! errno 1
Aug 30 01:38:09 PM  npm ERR! packrat@0.0.1 expo:export: `cd client && cp app.example.json app.json && npx expo export --platform web`
Aug 30 01:38:09 PM  npm ERR! Exit status 1
Aug 30 01:38:09 PM  npm ERR!
Aug 30 01:38:09 PM  npm ERR! Failed at the packrat@0.0.1 expo:export script.
Aug 30 01:38:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 30 01:38:09 PM  
Aug 30 01:38:09 PM  npm ERR! A complete log of this run can be found in:
Aug 30 01:38:09 PM  npm ERR!     /opt/render/.cache/_logs/2023-08-30T17_38_09_670Z-debug.log
Aug 30 01:38:09 PM  npm ERR! code ELIFECYCLE
Aug 30 01:38:09 PM  npm ERR! errno 1
Aug 30 01:38:09 PM  npm ERR! packrat@0.0.1 build:expo: `npm run expo:export`
Aug 30 01:38:09 PM  npm ERR! Exit status 1
Aug 30 01:38:09 PM  npm ERR!
Aug 30 01:38:09 PM  npm ERR! Failed at the packrat@0.0.1 build:expo script.
Aug 30 01:38:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 30 01:38:09 PM  
Aug 30 01:38:09 PM  npm ERR! A complete log of this run can be found in:
Aug 30 01:38:09 PM  npm ERR!     /opt/render/.cache/_logs/2023-08-30T17_38_09_875Z-debug.log
Aug 30 01:38:09 PM  npm ERR! code ELIFECYCLE
Aug 30 01:38:09 PM  npm ERR! errno 1
Aug 30 01:38:09 PM  npm ERR! packrat@0.0.1 build:prod: `npm run install:all && npm run build:expo && npm run build:tsc`
Aug 30 01:38:09 PM  npm ERR! Exit status 1
Aug 30 01:38:09 PM  npm ERR!
Aug 30 01:38:09 PM  npm ERR! Failed at the packrat@0.0.1 build:prod script.
Aug 30 01:38:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 30 01:38:10 PM  
Aug 30 01:38:10 PM  npm ERR! A complete log of this run can be found in:
Aug 30 01:38:10 PM  npm ERR!     /opt/render/.cache/_logs/2023-08-30T17_38_09_979Z-debug.log
Aug 30 01:38:10 PM  ==> Build failed 😞

```

**Comment by andrew-bierman** [comment]
Requests are nit making it through the zodParser I think

**Comment by raghavyuva** [comment]
> Are you able to run server on your side? I'm running into TS errors

server is not having any issues, it is running fine

**Comment by raghavyuva** [comment]
> Deploy logs
> 
> ```ts
> Aug 30 01:34:47 PM  > packrat@0.0.1 expo:export /opt/render/project/src
> Aug 30 01:34:47 PM  > cd client && cp app.example.json app.json && npx expo export --platform web
> Aug 30 01:34:47 PM  
> Aug 30 01:34:48 PM  Starting Metro Bundler
> Aug 30 01:38:08 PM  Web Bundling failed 200148ms
> Aug 30 01:38:09 PM  
> Aug 30 01:38:09 PM  Error: Unable to resolve module @trpc/server/observable from /opt/render/project/src/client/node_modules/@trpc/client/dist/index.mjs: @trpc/server/observable could not be found within the project or in these directories:
> Aug 30 01:38:09 PM    node_modules
> Aug 30 01:38:09 PM  > 1 | import { share, observableToPromise } from '@trpc/server/observable';
> Aug 30 01:38:09 PM      |                                             ^
> Aug 30 01:38:09 PM    2 | import { c as createChain } from './splitLink-4c75f7be.mjs';
> Aug 30 01:38:09 PM    3 | export { s as splitLink } from './splitLink-4c75f7be.mjs';
> Aug 30 01:38:09 PM    4 | import { T as TRPCClientError } from './TRPCClientError-fef6cf44.mjs';
> Aug 30 01:38:09 PM  Error: Unable to resolve module @trpc/server/observable from /opt/render/project/src/client/node_modules/@trpc/client/dist/index.mjs: @trpc/server/observable could not be found within the project or in these directories:
> Aug 30 01:38:09 PM    node_modules
> Aug 30 01:38:09 PM  > 1 | import { share, observableToPromise } from '@trpc/server/observable';
> Aug 30 01:38:09 PM      |                                             ^
> Aug 30 01:38:09 PM    2 | import { c as createChain } from './splitLink-4c75f7be.mjs';
> Aug 30 01:38:09 PM    3 | export { s as splitLink } from './splitLink-4c75f7be.mjs';
> Aug 30 01:38:09 PM    4 | import { T as TRPCClientError } from './TRPCClientError-fef6cf44.mjs';
> Aug 30 01:38:09 PM      at ModuleResolver.resolveDependency (/opt/render/project/src/client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
> Aug 30 01:38:09 PM      at DependencyGraph.resolveDependency (/opt/render/project/src/client/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
> Aug 30 01:38:09 PM      at Object.resolve (/opt/render/project/src/client/node_modules/metro/src/lib/transformHelpers.js:177:21)
> Aug 30 01:38:09 PM      at Graph._resolveDependencies (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
> Aug 30 01:38:09 PM      at Graph._processModule (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
> Aug 30 01:38:09 PM      at runMicrotasks (<anonymous>)
> Aug 30 01:38:09 PM      at processTicksAndRejections (internal/process/task_queues.js:95:5)
> Aug 30 01:38:09 PM      at async Graph._addDependency (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
> Aug 30 01:38:09 PM      at async Promise.all (index 0)
> Aug 30 01:38:09 PM      at async Graph._processModule (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
> Aug 30 01:38:09 PM  npm ERR! code ELIFECYCLE
> Aug 30 01:38:09 PM  npm ERR! errno 1
> Aug 30 01:38:09 PM  npm ERR! packrat@0.0.1 expo:export: `cd client && cp app.example.json app.json && npx expo export --platform web`
> Aug 30 01:38:09 PM  npm ERR! Exit status 1
> Aug 30 01:38:09 PM  npm ERR!
> Aug 30 01:38:09 PM  npm ERR! Failed at the packrat@0.0.1 expo:export script.
> Aug 30 01:38:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> Aug 30 01:38:09 PM  
> Aug 30 01:38:09 PM  npm ERR! A complete log of this run can be found in:
> Aug 30 01:38:09 PM  npm ERR!     /opt/render/.cache/_logs/2023-08-30T17_38_09_670Z-debug.log
> Aug 30 01:38:09 PM  npm ERR! code ELIFECYCLE
> Aug 30 01:38:09 PM  npm ERR! errno 1
> Aug 30 01:38:09 PM  npm ERR! packrat@0.0.1 build:expo: `npm run expo:export`
> Aug 30 01:38:09 PM  npm ERR! Exit status 1
> Aug 30 01:38:09 PM  npm ERR!
> Aug 30 01:38:09 PM  npm ERR! Failed at the packrat@0.0.1 build:expo script.
> Aug 30 01:38:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> Aug 30 01:38:09 PM  
> Aug 30 01:38:09 PM  npm ERR! A complete log of this run can be found in:
> Aug 30 01:38:09 PM  npm ERR!     /opt/render/.cache/_logs/2023-08-30T17_38_09_875Z-debug.log
> Aug 30 01:38:09 PM  npm ERR! code ELIFECYCLE
> Aug 30 01:38:09 PM  npm ERR! errno 1
> Aug 30 01:38:09 PM  npm ERR! packrat@0.0.1 build:prod: `npm run install:all && npm run build:expo && npm run build:tsc`
> Aug 30 01:38:09 PM  npm ERR! Exit status 1
> Aug 30 01:38:09 PM  npm ERR!
> Aug 30 01:38:09 PM  npm ERR! Failed at the packrat@0.0.1 build:prod script.
> Aug 30 01:38:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> Aug 30 01:38:10 PM  
> Aug 30 01:38:10 PM  npm ERR! A complete log of this run can be found in:
> Aug 30 01:38:10 PM  npm ERR!     /opt/render/.cache/_logs/2023-08-30T17_38_09_979Z-debug.log
> Aug 30 01:38:10 PM  ==> Build failed 😞
> ```

the build was successfull on my local

**Comment by andrew-bierman** [comment]
We still have an issue with validator not returning or calling next() i believe. Requests are not going past the validation middleware

**Comment by andrew-bierman** [comment]
On your side are you able to do all auth / CRUD stuff via either REST and tRPC ? Like from FE and postman is it all working on your end ?

**Comment by raghavyuva** [comment]
> On your side are you able to do all auth / CRUD stuff via either REST and tRPC ? Like from FE and postman is it all working on your end ?

trpc is working from my end

**Comment by andrew-bierman** [comment]
Ok I was able to get this running on my side, but I'm unable to make requests to our rest API in addition to trpc. Are you able to hit our traditional routes via postman and still get responses? i only get errors

**Comment by andrew-bierman** [comment]
Build still failing for deployment :(

`Sep 1 04:38:32 AM  ==> Cloning from https://github.com/andrew-bierman/PackRat...
Sep 1 04:38:33 AM  ==> Checking out commit 9ef03f9c175b5478fb149287b600890d7be2ddf8 in branch zod-integration
Sep 1 04:38:36 AM  ==> Downloading cache...
Sep 1 04:38:59 AM  ==> Transferred 499MB in 11s. Extraction took 10s.
Sep 1 04:39:00 AM  ==> Using Node version 14.17.0 (default)
Sep 1 04:39:00 AM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Sep 1 04:39:00 AM  ==> Running build command 'npm run build:prod'...
Sep 1 04:39:00 AM  
Sep 1 04:39:00 AM  > packrat@0.0.1 build:prod /opt/render/project/src
Sep 1 04:39:00 AM  > npm run install:all && npm run build:expo && npm run build:tsc
Sep 1 04:39:00 AM  
Sep 1 04:39:01 AM  
Sep 1 04:39:01 AM  > packrat@0.0.1 install:all /opt/render/project/src
Sep 1 04:39:01 AM  > npm install --prefix server && npm install --prefix client && npm install
Sep 1 04:39:01 AM  
Sep 1 04:39:38 AM  
Sep 1 04:39:38 AM  > nice-napi@1.0.2 install /opt/render/project/src/server/node_modules/nice-napi
Sep 1 04:39:38 AM  > node-gyp-build
Sep 1 04:39:38 AM  
Sep 1 04:39:38 AM  
Sep 1 04:39:38 AM  > msgpackr-extract@3.0.2 install /opt/render/project/src/server/node_modules/msgpackr-extract
Sep 1 04:39:38 AM  > node-gyp-build-optional-packages
Sep 1 04:39:38 AM  
Sep 1 04:39:38 AM  
Sep 1 04:39:38 AM  > bcrypt@5.1.1 install /opt/render/project/src/server/node_modules/bcrypt
Sep 1 04:39:38 AM  > node-pre-gyp install --fallback-to-build
Sep 1 04:39:38 AM  
Sep 1 04:39:39 AM  [bcrypt] Success: "/opt/render/project/src/server/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
Sep 1 04:39:39 AM  
Sep 1 04:39:39 AM  > protobufjs@6.11.4 postinstall /opt/render/project/src/server/node_modules/@grpc/proto-loader/node_modules/protobufjs
Sep 1 04:39:39 AM  > node scripts/postinstall
Sep 1 04:39:39 AM  
Sep 1 04:39:39 AM  
Sep 1 04:39:39 AM  > protobufjs@7.2.4 postinstall /opt/render/project/src/server/node_modules/google-gax/node_modules/protobufjs
Sep 1 04:39:39 AM  > node scripts/postinstall
Sep 1 04:39:39 AM  
Sep 1 04:39:39 AM  
Sep 1 04:39:39 AM  > protobufjs@7.2.5 postinstall /opt/render/project/src/server/node_modules/protobufjs
Sep 1 04:39:39 AM  > node scripts/postinstall
Sep 1 04:39:39 AM  
Sep 1 04:39:41 AM  added 827 packages from 656 contributors and audited 1478 packages in 39.734s
Sep 1 04:39:42 AM  
Sep 1 04:39:42 AM  63 packages are looking for funding
Sep 1 04:39:42 AM    run `npm fund` for details
Sep 1 04:39:42 AM  
Sep 1 04:39:42 AM  found 8 vulnerabilities (6 moderate, 2 critical)
Sep 1 04:39:42 AM    run `npm audit fix` to fix them, or `npm audit` for details
Sep 1 04:41:02 AM  
Sep 1 04:41:02 AM  > @fortawesome/fontawesome-common-types@6.4.2 postinstall /opt/render/project/src/client/node_modules/@fortawesome/fontawesome-common-types
Sep 1 04:41:02 AM  > node attribution.js
Sep 1 04:41:02 AM  
Sep 1 04:41:03 AM  Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com
Sep 1 04:41:03 AM  License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
Sep 1 04:41:03 AM  Copyright 2023 Fonticons, Inc.
Sep 1 04:41:03 AM  
Sep 1 04:41:03 AM  
Sep 1 04:41:03 AM  > protobufjs@6.11.4 postinstall /opt/render/project/src/client/node_modules/@grpc/proto-loader/node_modules/protobufjs
Sep 1 04:41:03 AM  > node scripts/postinstall
Sep 1 04:41:03 AM  
Sep 1 04:41:03 AM  
Sep 1 04:41:03 AM  > esbuild@0.19.2 postinstall /opt/render/project/src/client/node_modules/esbuild
Sep 1 04:41:03 AM  > node install.js
Sep 1 04:41:03 AM  
Sep 1 04:41:03 AM  
Sep 1 04:41:03 AM  > protobufjs@7.2.5 postinstall /opt/render/project/src/client/node_modules/protobufjs
Sep 1 04:41:03 AM  > node scripts/postinstall
Sep 1 04:41:03 AM  
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  > @fortawesome/fontawesome-svg-core@6.4.2 postinstall /opt/render/project/src/client/node_modules/@fortawesome/fontawesome-svg-core
Sep 1 04:41:04 AM  > node attribution.js
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com
Sep 1 04:41:04 AM  License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
Sep 1 04:41:04 AM  Copyright 2023 Fonticons, Inc.
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  > @fortawesome/free-solid-svg-icons@6.4.2 postinstall /opt/render/project/src/client/node_modules/@fortawesome/free-solid-svg-icons
Sep 1 04:41:04 AM  > node attribution.js
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com
Sep 1 04:41:04 AM  License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
Sep 1 04:41:04 AM  Copyright 2023 Fonticons, Inc.
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  
Sep 1 04:41:04 AM  > react-native-elements@3.4.3 postinstall /opt/render/project/src/client/node_modules/react-native-elements
Sep 1 04:41:04 AM  > opencollective-postinstall || exit 0
Sep 1 04:41:04 AM  
Sep 1 04:41:07 AM  added 2079 packages from 1070 contributors and audited 2356 packages in 84.618s
Sep 1 04:41:09 AM  
Sep 1 04:41:09 AM  153 packages are looking for funding
Sep 1 04:41:09 AM    run `npm fund` for details
Sep 1 04:41:09 AM  
Sep 1 04:41:09 AM  found 30 vulnerabilities (25 moderate, 1 high, 4 critical)
Sep 1 04:41:09 AM    run `npm audit fix` to fix them, or `npm audit` for details
Sep 1 04:41:22 AM  audited 1507 packages in 12.134s
Sep 1 04:41:22 AM  found 60 vulnerabilities (6 low, 21 moderate, 27 high, 6 critical)
Sep 1 04:41:22 AM    run `npm audit fix` to fix them, or `npm audit` for details
Sep 1 04:41:23 AM  
Sep 1 04:41:23 AM  > packrat@0.0.1 build:expo /opt/render/project/src
Sep 1 04:41:23 AM  > npm run expo:export
Sep 1 04:41:23 AM  
Sep 1 04:41:23 AM  
Sep 1 04:41:23 AM  > packrat@0.0.1 expo:export /opt/render/project/src
Sep 1 04:41:23 AM  > cd client && cp app.example.json app.json && npx expo export --platform web
Sep 1 04:41:23 AM  
Sep 1 04:41:24 AM  Starting Metro Bundler
Sep 1 04:44:53 AM  Web Bundling failed 208458ms
Sep 1 04:44:53 AM  
Sep 1 04:44:53 AM  Error: Unable to resolve module @trpc/server/observable from /opt/render/project/src/client/node_modules/@trpc/client/dist/index.mjs: @trpc/server/observable could not be found within the project or in these directories:
Sep 1 04:44:53 AM    node_modules
Sep 1 04:44:53 AM  > 1 | import { share, observableToPromise } from '@trpc/server/observable';
Sep 1 04:44:53 AM      |                                             ^
Sep 1 04:44:53 AM    2 | import { c as createChain } from './splitLink-4c75f7be.mjs';
Sep 1 04:44:53 AM    3 | export { s as splitLink } from './splitLink-4c75f7be.mjs';
Sep 1 04:44:53 AM    4 | import { T as TRPCClientError } from './TRPCClientError-fef6cf44.mjs';
Sep 1 04:44:53 AM  Error: Unable to resolve module @trpc/server/observable from /opt/render/project/src/client/node_modules/@trpc/client/dist/index.mjs: @trpc/server/observable could not be found within the project or in these directories:
Sep 1 04:44:53 AM    node_modules
Sep 1 04:44:53 AM  > 1 | import { share, observableToPromise } from '@trpc/server/observable';
Sep 1 04:44:53 AM      |                                             ^
Sep 1 04:44:53 AM    2 | import { c as createChain } from './splitLink-4c75f7be.mjs';
Sep 1 04:44:53 AM    3 | export { s as splitLink } from './splitLink-4c75f7be.mjs';
Sep 1 04:44:53 AM    4 | import { T as TRPCClientError } from './TRPCClientError-fef6cf44.mjs';
Sep 1 04:44:53 AM      at ModuleResolver.resolveDependency (/opt/render/project/src/client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
Sep 1 04:44:53 AM      at DependencyGraph.resolveDependency (/opt/render/project/src/client/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
Sep 1 04:44:53 AM      at Object.resolve (/opt/render/project/src/client/node_modules/metro/src/lib/transformHelpers.js:177:21)
Sep 1 04:44:53 AM      at Graph._resolveDependencies (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
Sep 1 04:44:53 AM      at Graph._processModule (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
Sep 1 04:44:53 AM      at runMicrotasks (<anonymous>)
Sep 1 04:44:53 AM      at processTicksAndRejections (internal/process/task_queues.js:95:5)
Sep 1 04:44:53 AM      at async Graph._addDependency (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
Sep 1 04:44:53 AM      at async Promise.all (index 0)
Sep 1 04:44:53 AM      at async Graph._processModule (/opt/render/project/src/client/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
Sep 1 04:44:53 AM  npm ERR! code ELIFECYCLE
Sep 1 04:44:53 AM  npm ERR! errno 1
Sep 1 04:44:53 AM  npm ERR! packrat@0.0.1 expo:export: `cd client && cp app.example.json app.json && npx expo export --platform web`
Sep 1 04:44:53 AM  npm ERR! Exit status 1
Sep 1 04:44:53 AM  npm ERR!
Sep 1 04:44:53 AM  npm ERR! Failed at the packrat@0.0.1 expo:export script.
Sep 1 04:44:53 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep 1 04:44:53 AM  
Sep 1 04:44:53 AM  npm ERR! A complete log of this run can be found in:
Sep 1 04:44:53 AM  npm ERR!     /opt/render/.cache/_logs/2023-09-01T08_44_53_836Z-debug.log
Sep 1 04:44:54 AM  npm ERR! code ELIFECYCLE
Sep 1 04:44:54 AM  npm ERR! errno 1
Sep 1 04:44:54 AM  npm ERR! packrat@0.0.1 build:expo: `npm run expo:export`
Sep 1 04:44:54 AM  npm ERR! Exit status 1
Sep 1 04:44:54 AM  npm ERR!
Sep 1 04:44:54 AM  npm ERR! Failed at the packrat@0.0.1 build:expo script.
Sep 1 04:44:54 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep 1 04:44:54 AM  
Sep 1 04:44:54 AM  npm ERR! A complete log of this run can be found in:
Sep 1 04:44:54 AM  npm ERR!     /opt/render/.cache/_logs/2023-09-01T08_44_54_049Z-debug.log
Sep 1 04:44:54 AM  npm ERR! code ELIFECYCLE
Sep 1 04:44:54 AM  npm ERR! errno 1
Sep 1 04:44:54 AM  npm ERR! packrat@0.0.1 build:prod: `npm run install:all && npm run build:expo && npm run build:tsc`
Sep 1 04:44:54 AM  npm ERR! Exit status 1
Sep 1 04:44:54 AM  npm ERR!
Sep 1 04:44:54 AM  npm ERR! Failed at the packrat@0.0.1 build:prod script.
Sep 1 04:44:54 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Sep 1 04:44:54 AM  
Sep 1 04:44:54 AM  npm ERR! A complete log of this run can be found in:
Sep 1 04:44:54 AM  npm ERR!     /opt/render/.cache/_logs/2023-09-01T08_44_54_239Z-debug.log
Sep 1 04:44:54 AM  ==> Build failed 😞
`

**Comment by andrew-bierman** [comment]
Swagger is not appearing did we remove that in one of the backend PRs for some reason? Would be perfect for testing these

**Comment by raghavyuva** [comment]
Please install server as a npm library to client , then everything will be resolved

**Comment by andrew-bierman** [comment]
owner_id error on /profile

**Comment by andrew-bierman** [comment]
/items page showing any data for you ?

**Comment by andrew-bierman** [comment]
dashboard blank on your end ?

**Comment by andrew-bierman** [comment]
Deployment is working now, just a couple thunks that broke after trpc migration

**Comment by andrew-bierman** [comment]
> Swagger is not appearing did we remove that in one of the backend PRs for some reason? Would be perfect for testing these

Resolved swagger issue

**Comment by andrew-bierman** [comment]
Should we be keeping the zod validations in a shared directory in root so we can use them on FE ?

**Comment by andrew-bierman** [comment]
This is super close. A couple things.

- [] We should add a comment somewhere on how we are setting up the REST and tRPC together. Because it looks like we have a Ie creating a basic route + controller, what should be done
- [] In reference to the token based auth middleware. Just for discussion purposes: can this be included in the new trpc + zod routes? How will we handle this from FE as now we make calls with the trpc library and not axios config

**Pull request merged**
