### PR TITLE
Landing Page Layour Design Changed

### PR DESCRIPTION
**Pull request by MuhammadHassan03**

### CODE REVIEW

**Review by EngrAJ8888 — APPROVED** [review]
the update looks great and this is ready to be merged. Thanks!

**Review by Isthisanmol — COMMENTED** [review]
The landing page looks great, but the theme change button isn't working. Also, I think it would be better if we could make the logo more visible.

**Comment by andrew-bierman** [comment]
@MuhammadHassan03 pls resolve conflicts then this should be good

**Comment by MuhammadHassan03** [comment]
> @MuhammadHassan03 pls resolve conflicts then this should be good

@andrew-bierman conflicts resolved :)

**Comment by andrew-bierman** [comment]
@Isthisanmol pls take quick look and make sure style changes work with your theming logic

**Comment by Isthisanmol** [comment]
@MuhammadHassan03 I suggest using colors from the theme instead of hardcoding them, so they can dynamically adjust according to the theme.

**Comment by MuhammadHassan03** [comment]
> @MuhammadHassan03 I suggest using colors from the theme instead of hardcoding them, so they can dynamically adjust according to the theme.

Yeah I forget to replace. Thanks for pointing out

**Comment by andrew-bierman** [comment]
@Isthisanmol pls double check and see if this breaks any of the stuff you have been working on recently

**Comment by Isthisanmol** [comment]
@MuhammadHassan03 It looks great on web but on native it was giving error regarding zindex

**Comment by MuhammadHassan03** [comment]
> @MuhammadHassan03 It looks great on web but on native it was giving error regarding zindex 

I don't have access to native 😕 will fix it after setup of native on my machine

**Comment by taronaleksanian** [comment]
@JewelTee @MuhammadHassan03 we don't need landing page on native app, let's show the current version of starting screen instead

**Comment by MuhammadHassan03** [comment]
> @JewelTee @MuhammadHassan03 we don't need landing page on native app, let's show the current version of starting screen instead

Sure

**Comment by taronaleksanian** [comment]
Now we show the old version of the intro screen on native, I'm merging this to development branch @JewelTee can you please test it there

**Pull request merged**
