### PR TITLE
show strips of selected profile

### PR DESCRIPTION
**Pull request by Tadjaur**

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur  - I've checked out the latest updates using the PR link provided, and I've observed that when viewing other users' profiles, the weights of the pack and destination of the trip aren't visible. Thanks! 

Please refer to this image: 
image.

**Comment by Tadjaur** [comment]
working on it!

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur, 
Thanks for the update! I can see that other users' trips are now displayed on their profiles, and the text is now visible. However, when attempting to view a trip and clicking on "View Profile," it results in an application error now. 

Please refer to the photos below. Thank you! 
image
image

**Comment by Tadjaur** [comment]
@EngrAJ8888 Now fixed!

**Comment by jeweltee** [comment]
@EngrAJ8888 @Tadjaur Confirmed, issue on this is now fixed.

**Comment by jeweltee** [comment]
@andrew-bierman  this is good to go for merging

**Comment by jeweltee** [comment]
@andrew-bierman this is good to go for merging

**Review by andrew-bierman — APPROVED** [review]
Lgtm

**Comment by jeweltee** [comment]
hi @Tadjaur this issues still persist on the testing branch, but it's working fine on the PR preview link. 
I am testing in this link - https://packrat-dev-qj5h.onrender.com/

**Pull request merged**
