### PR TITLE
hide chat and fix ui breaks

### PR DESCRIPTION
**Pull request by taronaleksanian**

### CODE REVIEW

**Review by JewelTee — COMMENTED** [review]
@taronaleksanian There are still broken UI. Please see images below. Thank you
Screenshot_2024-07-27-13-55-09-31_248012cd4184c9416d967f4c08ee0567
Screenshot_2024-07-27-13-58-07-47_248012cd4184c9416d967f4c08ee0567

**Review by EngrAJ8888 — CHANGES_REQUESTED** [review]
Hi @taronaleksanian, the pack screen is broken. I can't scroll past this page. 
image

**Comment by taronaleksanian** [comment]
@EngrAJ8888 @JewelTee the issues were fixed, is there any additional issues you faced, or we can start the release process?

**Comment by JewelTee** [comment]
@taronaleksanian issues are all fixed!

**Review by JewelTee — APPROVED** [review]

**Review by andrew-bierman — APPROVED** [review]
Lgtm

@JewelTee @EngrAJ8888 please make GitHub issues to re enable these features (and other that were hidden) after launch so we don't lose them

**Pull request merged**
