### PR TITLE
Update - Modal needs to be centered with screen

### PR DESCRIPTION
**Pull request by witehound**
Modal needs to be centered with the screen size : fixed issue by introducing tamagui.

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Can you rebase/merge with andrew_testing branch?

**Comment by andrew-bierman** [comment]
Buttons looking weirdly small

**Comment by andrew-bierman** [comment]
New modal looks good though :)

**Comment by witehound** [comment]
opening new pr!

**Pull request closed without merging**
