### PR TITLE
Fix native map download

### PR DESCRIPTION
**Pull request by Tadjaur**

### CODE REVIEW

**Review by JewelTee — COMMENTED** [review]
@Tadjaur hi! Downloaded Maps screen is empty even after successfully downloading a map. 
Screenshot_2024-07-22-00-10-21-11_248012cd4184c9416d967f4c08ee0567

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur, experienced the same issue. The "Download Maps' is empty.

**Comment by Tadjaur** [comment]
> Hi @Tadjaur, experienced the same issue. The "Download Maps' is empty. 

Yes, this PR needs a server deployment.

**Comment by Tadjaur** [comment]
I've split this PR into two for easier review.

- The first, #1115 contains only backend (server) updates.
- The second, this one contains only frontend (client) updates.

**Comment by andrew-bierman** [comment]
Server is deployed

**Comment by JewelTee** [comment]
@Tadjaur Download Maps Screen is fixed now. Thank You! 

@EngrAJ8888 please verify it on your end as well :)

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur @JewelTee, the download maps feature in the native app is now working on my end as well. After reinstalling the app, downloaded maps are saving correctly to my account.

@andrew-bierman this is ready to merge. 

Thank you!

**Review by EngrAJ8888 — APPROVED** [review]

**Pull request merged**
