### PR TITLE
Type Fix inisde UI directory

### PR DESCRIPTION
**Pull request by pinocchio-life-like**
Since Most of the type errors that are in UI directory come from "tamagui", I have tried many solutions but the right possible way I found is to update the type inside the module but it is inside the node_modules, and that is not possible. so I tried to avoid most of the type fixes by doing workarounds. but others I have set proper types on it and now we don't have type issue inside UI library.

check and let me know.

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Let's rebase this and get it merged, same with the other type PR

**Comment by pinocchio-life-like** [comment]
> Let's rebase this and get it merged, same with the other type PR

@andrew-bierman I did done rebase this, and added some updates.

**Comment by pinocchio-life-like** [comment]
Also there seems to be a lot of new type errors like inside server directory. 

I will rebase the already existing fixes and I will continue with the rest as well.

**Review by andrew-bierman — APPROVED** [review]

**Comment by andrew-bierman** [comment]
@jeweltee just double check everything looks good on site when you get a chance

**Comment by jeweltee** [comment]
@pinocchio-life-like hi!  I tested this PR and I encountered issues that had been resolved and merged to andrew_testing branch.

**Comment by pinocchio-life-like** [comment]
@jeweltee Hi, can you explain more please?

**Comment by jeweltee** [comment]
@andrew-bierman This has been updated, everything looks good now.

**Pull request merged**
