### PR TITLE
details page copy button and view owner button change

### PR DESCRIPTION
**Pull request by vipin4771234**

### CODE REVIEW

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
cards in feed still show View Owner

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
this shows the pack name not the username of owner

**Comment by andrew-bierman** [comment]
The cards in the /packs and profile should say something than view owner if the user is the owner

**Comment by vipin4771234** [comment]
> cards in feed still show View Owner

We don't have owner name access on feed data array. I have put the link only in pack/trip details page only. fetching owner for each card on feed page would be unnecessary.

**Review by vipin4771234 — COMMENTED** [review]
Changed View owner to view `${username}` and if user of pack is same as view user then show 'Your Profile'

**Comment by andrew-bierman** [comment]
> 

We could populate user on mongo query in backend ? Then we would have access. Just an idea.

**Review by vipin4771234 — COMMENTED** [review]
done

**Comment by vipin4771234** [comment]
Andrew Please verify new merge

**Pull request closed without merging**
