### PR TITLE
onClose implementation in copy pack modal

### PR DESCRIPTION
**Pull request by Isthisanmol**
onClose implementation in copy pack modal

### CODE REVIEW

**Review by andrew-bierman — APPROVED** [review]

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol - After reviewing the latest updates, I noticed that when users view other users' packs, the edit option should not be available to them. This option should only appear when they are viewing their own packs. Can we utilize the copy button instead of adding a dropdown menu? Thank you! 
Please see photo for reference.
image

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol - After reviewing the latest updates, I noticed that when users view other users' packs, the edit option should not be available to them. This option should only appear when they are viewing their own packs. Can we utilize the copy button instead of adding a dropdown menu? Thank you! Please see photo for reference. image

Should I remove the copy link functionality from this button and instead add the copy pack functionality? Alternatively, if the concern is restricting other users from editing and deleting the pack, we could make only the copy pack button visible to them.

**Comment by EngrAJ8888** [comment]
> > Hi @Isthisanmol - After reviewing the latest updates, I noticed that when users view other users' packs, the edit option should not be available to them. This option should only appear when they are viewing their own packs. Can we utilize the copy button instead of adding a dropdown menu? Thank you! Please see photo for reference. image
> 
> Should I remove the copy link functionality from this button and instead add the copy pack functionality? Alternatively, if the concern is restricting other users from editing and deleting the pack, we could make only the copy pack button visible to them.

Hi @Isthisanmol , that's correct. Just take out the edit/delete/save button and keep only the copy pack option. Also, please remove the copy link functionality.

**Comment by Isthisanmol** [comment]
> > > Hi @Isthisanmol - After reviewing the latest updates, I noticed that when users view other users' packs, the edit option should not be available to them. This option should only appear when they are viewing their own packs. Can we utilize the copy button instead of adding a dropdown menu? Thank you! Please see photo for reference. image
> > 
> > 
> > Should I remove the copy link functionality from this button and instead add the copy pack functionality? Alternatively, if the concern is restricting other users from editing and deleting the pack, we could make only the copy pack button visible to them.
> 
> Hi @Isthisanmol , that's correct. Just take out the edit/delete/save button and keep only the copy pack option. Also, please remove the copy link functionality. Thanks!

 Hi @EngrAJ8888, updated the functionality. Please check latest commit.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol  - The Copy Pack functionality is looking great!
We just need a few updates. Please review the list below:

- [ ] Some items don't aligned with others in the cloned pack I created.
image

- [ ] The 'Copy Pack' functionality should be removed from the cloned pack.
image

- [ ] The 'Copy Pack' functionality should not be available for users on their own packs. Users should only have the option to copy/clone packs when viewing other user's packs.
image

- [ ] Update the visibility of the Edit/Delete options for each item as they are currently not visible.
image


Thank you!

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol - The Copy Pack functionality is looking great! We just need a few updates. Please review the list below:
> 
>     * [ ]  Some items don't aligned with others in the cloned pack I created.
>       image
> 
>     * [ ]  The 'Copy Pack' functionality should be removed from the cloned pack.
>       image
> 
>     * [ ]  The 'Copy Pack' functionality should not be available for users on their own packs. Users should only have the option to copy/clone packs when viewing other user's packs.
>       image
> 
>     * [ ]  Update the visibility of the Edit/Delete options for each item as they are currently not visible.
>       image
> 
> 
> Thank you!

I'll work on this.Thanks.

**Comment by EngrAJ8888** [comment]
> > Hi @Isthisanmol - The Copy Pack functionality is looking great! We just need a few updates. Please review the list below:
> > ```
> > * [ ]  Some items don't aligned with others in the cloned pack I created.
> >   image
> > 
> > * [ ]  The 'Copy Pack' functionality should be removed from the cloned pack.
> >   image
> > 
> > * [ ]  The 'Copy Pack' functionality should not be available for users on their own packs. Users should only have the option to copy/clone packs when viewing other user's packs.
> >   image
> > 
> > * [ ]  Update the visibility of the Edit/Delete options for each item as they are currently not visible.
> >   image
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thank you!
> 
> Done the updates except the first one (alignment one). Please check. Thank you!

Hi @Isthisanmol - excellent work! We just need to adjust the alignment of the items, and then we can wrap this up. Thank you! :)

**Comment by Isthisanmol** [comment]
> > > Hi @Isthisanmol - The Copy Pack functionality is looking great! We just need a few updates. Please review the list below:
> > > ```
> > > * [ ]  Some items don't aligned with others in the cloned pack I created.
> > >   image
> > > 
> > > * [ ]  The 'Copy Pack' functionality should be removed from the cloned pack.
> > >   image
> > > 
> > > * [ ]  The 'Copy Pack' functionality should not be available for users on their own packs. Users should only have the option to copy/clone packs when viewing other user's packs.
> > >   image
> > > 
> > > * [ ]  Update the visibility of the Edit/Delete options for each item as they are currently not visible.
> > >   image
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Thank you!
> > 
> > 
> > Done the updates except the first one (alignment one). Please check. Thank you!
> 
> Hi @Isthisanmol - excellent work! We just need to adjust the alignment of the items, and then we can wrap this up. Thank you! :)

The alignment problem is not a ui problem. It has some api call issue. I have told Andrew about that already. He will look into that.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, got it! If that's the case, we can close this out. Thank you for working on this one!

@andrew-bierman - this is ready for merging.

**Pull request merged**
