### PR TITLE
Trip improvments

### PR DESCRIPTION
**Pull request by taronaleksanian**

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian - The update looks great! I'd like to add that trip details should be accurately reflected when viewing trips. I created a trip with Biking and Running as activities, but upon checking, the Activity section only displays the word "Trip" for both. Could you please take a look? I've attached a photo for reference. Thank you! 

image
image

**Comment by taronaleksanian** [comment]
Sure I will check it thanks

**Comment by andrew-bierman** [comment]
Good stuff, this would be cool if it filtered the search bar and nearby cards based on activity type ie selecting biking should not show a standard footpath. 

I believe we can update osm queries to optionally accept this new type

**Comment by taronaleksanian** [comment]
Yeah, great idea will implement it too!

**Pull request merged**
