### PR TITLE
Enhance light theme

### PR DESCRIPTION
**Pull request by Isthisanmol**

### CODE REVIEW

**Comment by JewelTee** [comment]
@Isthisanmol I noticed the sign-in component blends into the background, making it less prominent. Maybe we can adjust the contrast or consider using a darker background for the sign in form.
Screenshot 2024-07-26 144654

**Comment by JewelTee** [comment]
@Isthisanmol also from the home page, maybe we can change the background color of these buttons to a different blue shade (lighter) ? 

image

**Review by pinocchio-life-like — DISMISSED** [review]

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol,  I've noticed a few pages with broken UI. Please refer to the photos below.
image
image

- The "See All" button is overlapping with the "Create a Pack" button.
image

- The native app is crashing when creating or viewing a pack

**Comment by andrew-bierman** [comment]
the cards in /feed should be full width I believe

**Comment by andrew-bierman** [comment]
the sign in rounded box / card is not stretched to full width, it might look better how it was previously (only fit-content width)

**Comment by andrew-bierman** [comment]
great work those these are super small cleanup tasks, this is looking awesome

**Comment by taronaleksanian** [comment]
@andrew-bierman @JewelTee I'll fix those issues on my refacotiring branch, I merged this branch with mine.

**Pull request merged**
