### PR TITLE
826 trip score field and maps empty

### PR DESCRIPTION
**Pull request by Tadjaur**
- [X] Fix display linked pack information on trip details.
- [X] Fix map not showing on web next.js and vite.
- [ ] Trip score not showing

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur , just wanted to let you know that based on Andrew's feedback, the trip score update isn't a top priority at the moment. I've taken a look using the Cloudflare link, and the maps are still displaying empty. Thanks!

image

**Comment by jeweltee** [comment]
@Tadjaur hi. I just noticed when searching a trip location in the search bar then you click on the choices in the dropdown menu, it is not working. Here is a screen record for reference. Can you take a look if you have time? Thank You! 

https://github.com/andrew-bierman/PackRat/assets/166146993/1879acc7-e064-4f28-841d-48c02130711b

**Comment by Tadjaur** [comment]
> EngrAJ8888

The issues are now fixed. 
`Nearby trails` will appear after server deployment. 
The Nearby packs is client side fixe and should appear now.

**Comment by jeweltee** [comment]
@Tadjaur Hi. I just checked and the issues are now fixed. There are still several functionality issues but there's already a new ticket addressing those Trip Creation issues.  Please check #852 Thanks!

**Pull request merged**
