### PR TITLE
move map preview api call to backend

### PR DESCRIPTION
**Pull request by mikib0**

### CODE REVIEW

**Comment by andrew-bierman** [comment]
i'm getting some strange behavior on the trip create page. i can't get any map previews to display. tested:

- karachi (node)
- old rag (footway)
- new york (plot / area)

**Comment by andrew-bierman** [comment]
not sure if that is error from previous or specific to this branch, your new backend logic looks fine to me.

**Review by andrew-bierman — CHANGES_REQUESTED** [review]
bug on trip create ?

**Comment by mikib0** [comment]
> not sure if that is error from previous or specific to this branch, your new backend logic looks fine to me.

Hmm, I also get "action.meta.request is undefined" as I test it now. Everything was working fine when I tested yesterday; this is strange. Did you also get the same error or was yours different?

**Comment by andrew-bierman** [comment]
That was bug from recent middleware addition, try merging andrew_testing into branch or just commenting out our redux middleware's in store.js

**Comment by andrew-bierman** [comment]
i'm not getting any map previews to appear on my end, are you having same issue ?

**Comment by mikib0** [comment]
This is strange. Map previews work from my side.

**Pull request closed without merging**
