### PR TITLE
Mikibo user settings page

### PR DESCRIPTION
**Pull request by mikib0**
goto /settings

### CODE REVIEW

**Comment by andrew-bierman** [comment]
First name last name not prepopulating FYI. Can we connect these to real requests via auth store for updating name/email. Don't worry about storing profile picture until we get S3 set up

**Comment by andrew-bierman** [comment]
If the routes for changing name and email look to be too much work, that is fine we can merge this in for UI if needed

**Comment by mikib0** [comment]
> First name last name not prepopulating FYI. 

Turns out they don't exist on the user model, instead it's just a name field. I think it would be better to have firstName & lastName instead of just name 🤔.

> Can we connect these to real requests via auth store for updating name/email. Don't worry about storing profile picture until we get S3 set up

Yes, I planned to take the whole updating functionality (including password change) as another ticket. Will create another branch for that.

Let me refine the UI a bit and add section for password change, then we can merge it.

**Comment by andrew-bierman** [comment]
Great thanks. Username would be good to have also

**Comment by mikib0** [comment]
> Great thanks. Username would be good to have also

Yep, also added in the new commit.

**Comment by mikib0** [comment]
image

**Comment by andrew-bierman** [comment]
> > First name last name not prepopulating FYI. 
> 
> 
> 
> Turns out they don't exist on the user model, instead it's just a name field. I think it would be better to have firstName & lastName instead of just name 🤔.
> 
> 
> 
> > Can we connect these to real requests via auth store for updating name/email. Don't worry about storing profile picture until we get S3 set up
> 
> 
> 
> Yes, I planned to take the whole updating functionality (including password change) as another ticket. Will create another branch for that.
> 
> 
> 
> Let me refine the UI a bit and add section for password change, then we can merge it.

Agreed let's change to first and last and migrate existing if needed.

**Comment by andrew-bierman** [comment]
> image
> 
> 

This is looking good 👍

**Pull request merged**
