### PR TITLE
Refactor/modals

### PR DESCRIPTION
**Pull request by taronaleksanian**

### CODE REVIEW

**Comment by andrew-bierman** [comment]
I'm no longer seeing the X in top right corner of our modals, i don't think its due to this PR but while you are looking at these modals could you add that back if easy? If not easy we can take it up separately

**Comment by taronaleksanian** [comment]
> I'm no longer seeing the X in top right corner of our modals, i don't think its due to this PR but while you are looking at these modals could you add that back if easy? If not easy we can take it up separately

OK, sure I will review it, and try to fix it ASAP

**Comment by taronaleksanian** [comment]
> I'm no longer seeing the X in top right corner of our modals, i don't think its due to this PR but while you are looking at these modals could you add that back if easy? If not easy we can take it up separately

done

**Review by andrew-bierman — APPROVED** [review]
nice job with this :)

**Pull request merged**
