### PR TITLE
Fix/theme text visibility

### PR DESCRIPTION
**Pull request by pinocchio-life-like**

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like, thank you for making the updates! 
I'd like to add some necessary updates. There are texts that are not in the trip creation/viewing field. Additionally, there are still white lines present in the item column, weather section, and pack scoring. Could we remove these to achieve a seamless background? Please refer to the photo below for reference. Thank you!

image
image

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 Ok, Got it.

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like Thanks! 

Adding also the login page.
image

**Comment by jeweltee** [comment]
@pinocchio-life-like adding this one too, the icon on the Old Password field is not that visible. Please see image below thanks! 
fb837f12-ab8a-4633-8460-7f27e54accb3

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 @jeweltee Check the updates and lmk, Thanks!

**Comment by jeweltee** [comment]
@pinocchio-life-like hi. Thanks the update looks good to me, I'll double-check it with @EngrAJ8888

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 Updated

**Review by EngrAJ8888 — APPROVED** [review]

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like - great job! the update looks great!

@andrew-bierman - this is good for merging.

**Pull request merged**
