### PR TITLE
Add paginated bento table to itemstable

### PR DESCRIPTION
**Pull request by Isthisanmol**

### CODE REVIEW

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol - I've checked the updates on the new link, and it seems that the next page button is not working. I can't move to another page of items. Could you please look into this? Thank you! 
image

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol - I've checked the updates on the new link, and it seems that the next page button is not working. I can't move to another page of items. Could you please look into this? Thank you! image

When you set the limit to 10, only 10 items will be displayed per page, resulting in a single page of items. However, if you set the limit to 50, you will see 5 pages, each containing 10 items.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, I understand your point, but my thought process is that when you choose a limit, such as 10 for example, the app should display 10 items on the first page, with additional items shown on the next pages. However, if I choose 20, the first page should display 20 items and so on.

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol, I understand your point, but my thought process is that when you choose a limit, such as 10 for example, the app should display 10 items on the first page, with additional items shown on the next pages. However, if I choose 20, the first page should display 20 items and so on.

I'll update that.Thankyou.

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, Please check this again. I have made the updates.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, the update looks great! However, could we make a small fix to the text? The dropdown text isn't updating - it still shows 'Choose a Value'. Can we update this first, and then we'll be ready to merge. Thank you! :)
image

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, I'd also like to suggest adding an option for 'All items' in the sorting. Thank you! :)

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol, I'd also like to suggest adding an option for 'All items' in the sorting. Thank you! :)

Updated both. Please check.

**Comment by andrew-bierman** [comment]
@Isthisanmol @EngrAJ8888 merging this, pls take up comments on new PR

**Review by andrew-bierman — APPROVED** [review]
Lgtm nice job

**Pull request merged**
