### PR TITLE
Success response handler

### PR DESCRIPTION
**Pull request by raghavyuva**

### CODE REVIEW

**Comment by andrew-bierman** [comment]
Does this fully replace the other error specific PR you have up?

**Comment by andrew-bierman** [comment]
Error on preview deploy 

Aug 23 05:59:39 AM  > packrat@0.0.1 build:tsc /opt/render/project/src
Aug 23 05:59:39 AM  > cd server && npm run build
Aug 23 05:59:39 AM  
Aug 23 05:59:40 AM  
Aug 23 05:59:40 AM  > server@1.0.0 build /opt/render/project/src/server
Aug 23 05:59:40 AM  > NODE_OPTIONS=--max_old_space_size=4096 tsc
Aug 23 05:59:40 AM  
Aug 23 06:00:15 AM  src/controllers/item/addItemGlobal.ts(3,33): error TS2307: Cannot find module '../../helpers/response' or its corresponding type declarations.
Aug 23 06:00:15 AM  npm ERR! code ELIFECYCLE
Aug 23 06:00:15 AM  npm ERR! errno 2
Aug 23 06:00:15 AM  npm ERR! server@1.0.0 build: `NODE_OPTIONS=--max_old_space_size=4096 tsc`
Aug 23 06:00:15 AM  npm ERR! Exit status 2
Aug 23 06:00:15 AM  npm ERR!
Aug 23 06:00:15 AM  npm ERR! Failed at the server@1.0.0 build script.
Aug 23 06:00:15 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 23 06:00:15 AM  
Aug 23 06:00:15 AM  npm ERR! A complete log of this run can be found in:
Aug 23 06:00:15 AM  npm ERR!     /opt/render/.cache/_logs/2023-08-23T10_00_15_245Z-debug.log
Aug 23 06:00:15 AM  npm ERR! code ELIFECYCLE
Aug 23 06:00:15 AM  npm ERR! errno 2
Aug 23 06:00:15 AM  npm ERR! packrat@0.0.1 build:tsc: `cd server && npm run build`
Aug 23 06:00:15 AM  npm ERR! Exit status 2
Aug 23 06:00:15 AM  npm ERR!
Aug 23 06:00:15 AM  npm ERR! Failed at the packrat@0.0.1 build:tsc script.
Aug 23 06:00:15 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 23 06:00:15 AM  
Aug 23 06:00:15 AM  npm ERR! A complete log of this run can be found in:
Aug 23 06:00:15 AM  npm ERR!     /opt/render/.cache/_logs/2023-08-23T10_00_15_264Z-debug.log
Aug 23 06:00:15 AM  npm ERR! code ELIFECYCLE
Aug 23 06:00:15 AM  npm ERR! errno 2
Aug 23 06:00:15 AM  npm ERR! packrat@0.0.1 build:prod: `npm run install:all && npm run build:expo && npm run build:tsc`
Aug 23 06:00:15 AM  npm ERR! Exit status 2
Aug 23 06:00:15 AM  npm ERR!
Aug 23 06:00:15 AM  npm ERR! Failed at the packrat@0.0.1 build:prod script.
Aug 23 06:00:15 AM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 23 06:00:15 AM  
Aug 23 06:00:15 AM  npm ERR! A complete log of this run can be found in:
Aug 23 06:00:15 AM  npm ERR!     /opt/render/.cache/_logs/2023-08-23T10_00_15_282Z-debug.log
Aug 23 06:00:15 AM  ==> Build failed 😞

**Comment by raghavyuva** [comment]
> Does this fully replace the other error specific PR you have up?

yes

**Comment by andrew-bierman** [comment]
Put conflict resolution on another branch and merged in FYI

**Pull request closed without merging**
